spring.application.name=spring-merch-store
spring.ai.anthropic.api-key=${ANTHROPIC_API_KEY}

management.endpoints.web.exposure.include=*

arconia.observations.conventions.opentelemetry.generative-ai.inference.capture-content=span-attributes
arconia.observations.conventions.opentelemetry.generative-ai.inference.include-tool-definitions=true
arconia.observations.conventions.opentelemetry.generative-ai.tool-execution.include-content=true